### ISSUE TITLE
Init TODO

### ISSUE THREAD

**Issue by ZitaNemeckova** [himdel/poc-components#1]
- [ ] update readme - how to run test, storybook, guidelines
- [x] add Jest
  - [ ] github action (#2)
- [x] add Storybook
  - [ ] set autobuild, deploy ..surge?
  - [x] patternfly css
- [ ] add POC components
  - [x] EmptyState
  - [ ] Header
  - [x] 404
  - [x] 500
- [x] build, release npm package
  - [ ] release on push
- [x] linters
  - [ ] github action
- [ ] dependabot
- [ ] add CHANGELOG/CHANGES.md

Discussion
- [ ] lingui
- [ ] styled-components / css?
